In [2]:
import numpy as np

In [2]:
a= np.array([1,.3, 43,54,9.65])

In [3]:
b= a[2:]

In [4]:
b[0]=33
q = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
              [[23, 43, 4, 5],[1, 2, 3, 7],[5, 6, 7, 8]]])


In [15]:
q[1,2,2]

np.int64(7)

In [47]:
# The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
# q.shape

# The number of dimensions of an array is contained in the ndim attribute.
# q.ndim

# The fixed, total number of elements in array is contained in the size attribute.
# q.size

# The data type is recorded in the dtype attribute.
q.dtype
# type(q)

dtype('int64')

In [6]:
d = {1: 'A'}
b= np.array([[1,23,3], 
             [3, d,9], 
             [5,6,6]])


In [9]:
print(b.dtype)
b.dtype

object


dtype('O')

In [16]:
# Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:
# np.zeros(4)

# Or an array filled with 1’s:
# np.ones(3)

# The function empty creates an array whose initial content is random and depends on the state of the memory.
# np.empty(2)

# The NumPy full() function in Python is used to create an array with a specified shape and fill it with a given value.
# np.full((3,2,4),99)
# Ex- Return array with dtype=str
np.full(shape=(3,2,4),fill_value='555', dtype='<U3')

array([[['555', '555', '555', '555'],
        ['555', '555', '555', '555']],

       [['555', '555', '555', '555'],
        ['555', '555', '555', '555']],

       [['555', '555', '555', '555'],
        ['555', '555', '555', '555']]], dtype='<U3')

In [32]:
# You can create an array with a range of elements:
# np.arange(2,19,2.3)

# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interva
np.linspace(0, 1007, num=20)

array([   0.,   53.,  106.,  159.,  212.,  265.,  318.,  371.,  424.,
        477.,  530.,  583.,  636.,  689.,  742.,  795.,  848.,  901.,
        954., 1007.])

In [25]:
np.sqrt(-1)
# np.array([2])/0

C:\Users\USER\AppData\Local\Temp\ipykernel_14356\3236165812.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


np.float64(nan)

In [37]:
a1= np.array([1,2,3])
a2 = np.array([[3,4,5],
             [5,6,7]])

# a2@a1
a1*a2

array([[ 3,  8, 15],
       [ 5, 12, 21]])

In [24]:
v = np.array([2,3,4])
M = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
p= v@M
q = M@v
r= np.dot(v,M)
s= np.dot(M, v)
print(p, q, r,s)

[42 51 60] [20 47 74] [42 51 60] [20 47 74]


In [37]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (arr>=5)
print(arr[five_up])
even = (arr%2==0)
print(a[even])

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [51]:
a1 = np.array([[1,1],[2,2],[5,5]])
a2 = np.array([[3,3],[4,4],[6,6]])
# np.vstack((a1,a2))
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4],
       [5, 5, 6, 6]])

In [69]:
data = np.array([10,20])
ones = np.ones(2, dtype = int)
ones*data

array([10, 20])

In [86]:
ss = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
sv = ss.sum( axis=0) # Use axis=0 to apply a method down each column, or to the row labels (the index).
sc = ss.sum(axis=1) # Use axis=1 to apply a method across each row, or to the column labels.
sv, sc

(array([12, 15, 18]), array([ 6, 15, 24]))