In [14]:
import numpy as np

In [2]:
a= np.array([1,.3, 43,54,9.65])

In [3]:
b= a[2:]

In [4]:
b[0]=33
q = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], 
              [[23, 43, 4, 5],[1, 2, 3, 7],[5, 6, 7, 8]]])


In [15]:
q[1,2,2]

np.int64(7)

In [47]:
# The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
# q.shape

# The number of dimensions of an array is contained in the ndim attribute.
# q.ndim

# The fixed, total number of elements in array is contained in the size attribute.
# q.size

# The data type is recorded in the dtype attribute.
q.dtype
# type(q)

dtype('int64')

In [6]:
d = {1: 'A'}
b= np.array([[1,23,3], 
             [3, d,9], 
             [5,6,6]])


In [9]:
print(b.dtype)
b.dtype

object


dtype('O')

In [16]:
# Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:
# np.zeros(4)
# Create an random(empty) array with datatype float and order "C"
np.empty(3,float,'C')


# Or an array filled with 1’s:
# np.ones(3)

# The function empty creates an array whose initial content is random and depends on the state of the memory.
# np.empty(2)

# The NumPy full() function in Python is used to create an array with a specified shape and fill it with a given value.
# np.full((3,2,4),99)
# Example - Return array with dtype=str
np.full(shape=(3,2,4),fill_value='555', dtype='<U3')

array([[['555', '555', '555', '555'],
        ['555', '555', '555', '555']],

       [['555', '555', '555', '555'],
        ['555', '555', '555', '555']],

       [['555', '555', '555', '555'],
        ['555', '555', '555', '555']]], dtype='<U3')

In [32]:
# You can create an array with a range of elements:
# np.arange(2,19,2.3)

# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interva
np.linspace(0, 1007, num=20)

array([   0.,   53.,  106.,  159.,  212.,  265.,  318.,  371.,  424.,
        477.,  530.,  583.,  636.,  689.,  742.,  795.,  848.,  901.,
        954., 1007.])

In [25]:
np.sqrt(-1)
# np.array([2])/0

C:\Users\USER\AppData\Local\Temp\ipykernel_14356\3236165812.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)


np.float64(nan)

In [37]:
a1= np.array([1,2,3])
a2 = np.array([[3,4,5],
             [5,6,7]])

# a2@a1
a1*a2

array([[ 3,  8, 15],
       [ 5, 12, 21]])

In [24]:
v = np.array([2,3,4])
M = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
p= v@M
q = M@v
r= np.dot(v,M)
s= np.dot(M, v)
print(p, q, r,s)

[42 51 60] [20 47 74] [42 51 60] [20 47 74]


In [37]:
arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
five_up = (arr>=5)
print(arr[five_up])
even = (arr%2==0)
print(a[even])

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


In [51]:
a1 = np.array([[1,1],[2,2],[5,5]])
a2 = np.array([[3,3],[4,4],[6,6]])
# np.vstack((a1,a2))
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4],
       [5, 5, 6, 6]])

In [227]:
data = np.array([10,20])
# ones = np.ones(2, dtype = int)
ones= np.ones((4,3,2), dtype=int)
ones
# ones*data

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [171]:
ss = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                [13,14,15,16,17,18]])
rows = ss.sum(axis=0) # Use axis=0 to apply a method down each column, or to the row labels (the index).
cols = ss.sum(axis=1) # Use axis=1 to apply a method across each row, or to the column labels.
rows, cols

(array([21, 24, 27, 30, 33, 36]), array([21, 57, 93]))

In [172]:
vv =ss.reshape(3,3,2)
# print(vv)
x =vv.sum(axis=1)
y =vv.sum(axis=2)
z =vv.sum(axis=0)
x, y, z, vv

(array([[ 9, 12],
        [27, 30],
        [45, 48]]),
 array([[ 3,  7, 11],
        [15, 19, 23],
        [27, 31, 35]]),
 array([[21, 24],
        [27, 30],
        [33, 36]]),
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],
 
        [[ 7,  8],
         [ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16],
         [17, 18]]]))

In [186]:
mean= vv.mean(axis=2)
maxi = vv.max(axis=0)
mini = vv.min(axis=1)
mean, maxi, mini

(array([[ 1.5,  3.5,  5.5],
        [ 7.5,  9.5, 11.5],
        [13.5, 15.5, 17.5]]),
 array([[13, 14],
        [15, 16],
        [17, 18]]),
 array([[ 1,  2],
        [ 7,  8],
        [13, 14]]))

In [7]:
# Creating a Random Number Generator
rng = np.random.default_rng()
# this line creates an instance of NumPy's Generator. The method np.random.default_rng()
# by default uses the PCG64 bit generator.
rng.random((4,3))
# You can generate a 2 x 4 array of random integers between 0 and 4 with:
rng.integers(5, size=(2,4))

array([[0, 4, 1, 4],
       [0, 3, 0, 1]])

In [29]:
# How to get unique items and counts
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
# unique_values
# If the axis argument isn’t passed, your 2D array will be flattened.
# If you want to get the unique rows or columns, make sure to pass the axis argument. 
# To find the unique rows, specify axis=0 and for columns, specify axis=1.
unique_rows = np.unique(a_2d, axis=0)
# To get the unique rows, index position, and occurrence count, you can use:
unique_rows, indices, count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
indices, count

(array([0, 1, 2]), array([2, 1, 1]))

In [26]:
arr = np.arange(6).reshape((2,3))
arr, arr.T
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [54]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# You can also reverse the column at index position 1 (the second column):
arr_2dflip = np.flip(arr_2d[:, 1])
arr_2dflip, arr_2d
# Docstring
# arr_2d?

(array([10,  6,  2]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))